---
- name: sample book
  hosts: ansible_client1
  remote_user: root
  become: true
  tasks:
    - name: install httpd
      yum:
          name: httpd
          state: latest
    - name: run httpd
      service:
          name: httpd
          state: started
    - name: create content
      copy:
          content: "Congratulation on the Ansible Installation"
          dest: /var/www/html/index.html
